<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "pembimbing".
 *
 * @property string $nip_dosen
 * @property int $id_tugas_akhir
 * @property int $level
 *
 * @property TugasAkhir $tugasAkhir
 * @property Dosen $Dosen
 */
class Dibimbing extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'dibimbing';
    }

    public static function primaryKey()
    {
        return ['id_tugas_akhir', 'nip_dosen']; // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_tugas_akhir', 'level'], 'required'],
            [['id_tugas_akhir', 'level'], 'integer'],
            [['nip_dosen'], 'string', 'max' => 18],
            [['id_tugas_akhir', 'nip_dosen'], 'unique', 'targetAttribute' => ['id_tugas_akhir', 'nip_dosen']],
//            [['id_tugas_akhir'], 'exist', 'skipOnError' => true, 'targetClass' => TugasAkhir::className(), 'targetAttribute' => ['id_tugas_akhir' => 'id']],
//            [['nip_dosen'], 'exist', 'skipOnError' => true, 'targetClass' => Dosen::className(), 'targetAttribute' => ['nip_dosen' => 'nip']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'nip_dosen' => 'Nip Dosen',
            'id_tugas_akhir' => 'Id Tugas Akhir',
            'level' => 'Level',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTugasAkhir()
    {
        return $this->hasOne(TugasAkhir::className(), ['id' => 'id_tugas_akhir']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDosen()
    {
        return $this->hasOne(Dosen::className(), ['nip' => 'nip_dosen']);
    }
}
